baseURL: https://blog.geheimesite.nl/
defaultContentLanguage: nl
timeZone: Europe/Amsterdam
paginate: 16
enableEmoji: true
theme: picardo

author:
    name: Robin Boers
    image: https://geheimesite.nl/images/me_optimized.webp
    about: I'm a webdesigner, programmer, and nerd living in the Netherlands. I'm 15 years old and I currently work at Qdentity.

publishDir: dist
themesDir: src/themes
archetypeDir: src/archetypes

module:
    mounts:
        - source: src
          target: assets
          includeFiles: assets/**/*
        - source: src/static
          target: static
        - source: src/layouts
          target: layouts
        - source: src/data
          target: data

minify:
    disableHTML: true
    minifyOutput: true

params:
    github_repo: RobinBoers/blog
    webmention_url: https://webmention.io/geheimesite.nl/webmention
    pingback_url: https://webmention.io/geheimesite.nl/xmlrpc
    main_sections: posts

languages:
    nl:
        contentDir: content/nl
        languageName: Nederlands
        languageCode: nl
        title: Webdevelopment-En-Meer
        params:
            description: Ik ben Robin, en ik ben 15 jaar oud. Ik woon in Maasssluis. Ik ben webdesigner en programmeur en ik werk momenteel bij Qdentity. Ik specialiseer me vooral in webdevelopment, maar doe ook wel eens backend stuff. Op dit blog post ik regelmatig over mijn hobby en dingen die me interesseren.
            main_site_url: https://geheimesite.nl
        copyright: Webdesigner en Elixir programmeur sinds 2017.

    en:
        contentDir: content/en
        languageName: English
        languageCode: en
        title: ThatCrazyWebdev
        params:
            description: Hi! My name is Robin. I’m an enthusiastic developer from the Netherlands. I mostly talk about programming and new stuff I learn, but also about software-development as a whole. I’m also a Linux enthusiast, so you’ll also see me talk about Linux and open-source in general a lot.
            main_site_url: https://geheimesite.nl/en
        copyright: Webdesigner and Elixir programmer since 2017.

markup:
    highlight:
        codeFences: true
        guessSyntax: false
        noClasses: true
        noHl: false
        style: github-dark
        tabWidth: 4

    goldmark:
        renderer:
            unsafe: true

enableRobotsTXT: false
disableHugoGeneratorInject: true

enableGitInfo: true
frontmatter:
    lastmod:
        - lastmod
        - :git
        - date
        - publishDate

outputs:
    home: ["HTML", "JSON", "RSS"]
